// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import VisibilityController from "./visibility_controller";
application.register("visibility", VisibilityController);

import ModalController from "./modal_controller";
application.register("modal", ModalController);

import TimerController from "./timer_controller";
application.register("timer", TimerController);
